# Chargement de donnees

In [4]:
import pandas as pd

# Charger les données
df = pd.read_csv("../data/superstore.csv")

# Aperçu
print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680

# Structure du dataset

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

# Nettoyage

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales'],
      dtype='str')

# Valeurs manquantes

In [3]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

# Postal Code contient 11 valuers manquantes dont il faudra supprimer

In [10]:
df['postal_code'] = df['postal_code'].fillna(0)

# Supprimer les doublons

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df = df.drop_duplicates()

# Conversion des donnees

In [15]:
df['order_date'] = pd.to_datetime(df['order_date'], format='%d/%m/%Y')

# Feature engineering

In [16]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()

# Verification finale

In [17]:
df.describe()

,row_id,order_date,postal_code,sales,year,month
count,9800.000000,9800,9800.000000,9800.000000,9800.000000,9800.000000
mean,4900.500000,2017-05-01 05:13:51.673469,55211.280918,230.769059,2016.724184,7.818469
min,1.000000,2015-01-03 00:00:00,0.000000,0.444000,2015.000000,1.000000
25%,2450.750000,2016-05-24 00:00:00,23223.000000,17.248000,2016.000000,5.000000
50%,4900.500000,2017-06-26 00:00:00,57551.000000,54.490000,2017.000000,9.000000
75%,7350.250000,2018-05-15 00:00:00,90008.000000,210.605000,2018.000000,11.000000
max,9800.000000,2018-12-30 00:00:00,99301.000000,22638.480000,2018.000000,12.000000
std,2829.160653,NaN,32076.677954,626.651875,1.123984,3.281905

# Sauvegarder les donnees propres

In [18]:
df.to_csv("../data/cleaned_superstore.csv", index=False)

# ===========================
# KEY PERFORMANCE INDICATORS
# ===========================

In [22]:
print(df.columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales', 'year', 'month', 'month_name'],
      dtype='str')

# Générer un profit entre -20% et +30% des ventes

In [24]:
import numpy as np

df['profit'] = df['sales'] * np.random.uniform(-0.2, 0.3, size=len(df))
print(df.profit)

0       -10.921281
1       185.065817
2         3.868007
3       -92.885013
4         1.552445
           ...
9795      0.071682
9796      2.514662
9797    -44.252427
9798      1.910744
9799      2.567741
Name: profit, Length: 9800, dtype: float64

In [25]:
df.to_csv("../data/cleaned_superstore.csv", index=False)

# Compute total sales, profits, and orders

In [26]:
total_sales = df['sales'].sum()
total_profit = df['profit'].sum()
total_orders = df['order_id'].nunique()

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Orders:", total_orders)

Total Sales: 2261536.7827
Total Profit: 123503.36435095863
Total Orders: 4922

#  Insight: 
# The company genreated X revenue with Y profit across Z orders.
# indication a heathy business performance.

# Top produits

In [28]:
top_products = df.groupby('product_name')['sales'].sum() \
                 .sort_values(ascending=False).head(10)

top_products

product_name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: sales, dtype: float64

# Insight:
# A small number of products generate a large portion of revenue (Pareto effect).

# Categories les plus rentables

In [29]:
category_profit = df.groupby('category')['profit'].sum() \
                    .sort_values(ascending=False)

category_profit

category
Technology         52082.994109
Office Supplies    41558.532242
Furniture          29861.838000
Name: profit, dtype: float64

# Insight:
# Technology category is the most profitable, while Furniture shows lower margins.

# Analyse temporelle

In [30]:
monthly_sales = df.groupby(['year', 'month'])['sales'].sum().reset_index()

monthly_sales

    year  month        sales
0   2015      1   14205.7070
1   2015      2    4519.8920
2   2015      3   55205.7970
3   2015      4   27906.8550
4   2015      5   23644.3030
5   2015      6   34322.9356
6   2015      7   33781.5430
7   2015      8   27117.5365
8   2015      9   81623.5268
9   2015     10   31453.3930
10  2015     11   77907.6607
11  2015     12   68167.0585
12  2016      1   18066.9576
13  2016      2   11951.4110
14  2016      3   32339.3184
15  2016      4   34154.4685
16  2016      5   29959.5305
17  2016      6   23599.3740
18  2016      7   28608.2590
19  2016      8   36818.3422
20  2016      9   63133.6060
21  2016     10   31011.7375
22  2016     11   75249.3995
23  2016     12   74543.6012
24  2017      1   18542.4910
25  2017      2   22978.8150
26  2017      3   51165.0590
27  2017      4   38679.7670
28  2017      5   56656.9080
29  2017      6   39724.4860
30  2017      7   38320.7830
31  2017      8   30542.2003
32  2017      9   69193.3909
33  2017     10   59583.0330
34  2017     11   79066.4958
35  2017     12   95739.1210
36  2018      1   43476.4740
37  2018      2   19920.9974
38  2018      3   58863.4128
39  2018      4   35541.9101
40  2018      5   43825.9822
41  2018      6   48190.7277
42  2018      7   44825.1040
43  2018      8   62837.8480
44  2018      9   86152.8880
45  2018     10   77448.1312
46  2018     11  117938.1550
47  2018     12   83030.3888

# Ventes par mois

In [31]:
df.groupby('month_name')['sales'].sum().sort_values(ascending=False)

month_name
November     350161.7110
December     321480.1695
September    300103.4117
October      199496.2947
March        197573.5872
August       157315.9270
May          154086.7237
June         145837.5233
July         145535.6890
April        136283.0006
January       94291.6296
February      59371.1154
Name: sales, dtype: float64

# Insight:
# Sales peak during end-of-year months, likely due to seasonal demand.

# Performance par region

In [32]:
region_sales = df.groupby('region')['sales'].sum().sort_values(ascending=False)
region_profit = df.groupby('region')['profit'].sum().sort_values(ascending=False)

region_sales
region_profit

region
West       37707.780241
East       32799.178137
South      27388.837711
Central    25607.568262
Name: profit, dtype: float64

# Insight:
# Some regions generate high sales but low profit → potential inefficiency.

# Top clients

In [33]:
top_customers = df.groupby('customer_name')['sales'].sum() \
                  .sort_values(ascending=False).head(10)

top_customers

customer_name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: sales, dtype: float64

# Insight:
# A small number of customers contribute significantly to total revenue.

# Detection des problemes business (tres fort en entretien)

In [34]:
loss_making = df[df['profit'] < 0]
loss_making.groupby('category')['profit'].sum()

category
Furniture         -30794.557399
Office Supplies   -25610.450190
Technology        -27888.981477
Name: profit, dtype: float64

# Insight:
# Certain categories generate consistent losses and should be investigated.