In [16]:
import pandas as pd

#charger dataset
df = pd.read_csv("../data/superstore.csv")

#Appercu
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [17]:
#structure dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [43]:
# Nettayage
# 4.1: Standardiser les noms de colonnes (Tres important pour SQL et Python)
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub-category',
       'product_name', 'sales'],
      dtype='str')

In [28]:
# 4.2: Valeurs manquantes
df.isnull().sum()

row_id           0
order_id         0
order_date       0
ship_date        0
ship_mode        0
customer_id      0
customer_name    0
segment          0
country          0
city             0
state            0
postal_code      0
region           0
product_id       0
category         0
sub-category     0
product_name     0
sales            0
dtype: int64

In [44]:
#Supprimer les valeurs manquantes ici Postal Code
df = df.dropna(subset=['postal_code'])

In [31]:
# 4.3 Doublons (ici pas de doublons sinon on devais faire df = df.drop-duplicates())
df.duplicated().sum()

np.int64(0)

In [57]:
#4.4  Conversion des donnees en format de date et time
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [55]:
#4.5 Feature engineering (tres important)
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()

In [ ]:
# 4.6 verifiction 
df.describe()

,row_id,order_date,postal_code,sales,year,month
count,9789.000000,3955,9789.000000,9789.000000,3955.000000,3955.000000
mean,4896.705588,2017-03-14 18:03:54.841972,55273.322403,230.116193,2016.728445,6.452845
min,1.000000,2015-01-02 00:00:00,1040.000000,0.444000,2015.000000,1.000000
25%,2449.000000,2016-04-05 00:00:00,23223.000000,17.248000,2016.000000,3.000000
50%,4896.000000,2017-05-02 00:00:00,58103.000000,54.384000,2017.000000,6.000000
75%,7344.000000,2018-03-07 00:00:00,90008.000000,210.392000,2018.000000,9.000000
max,9800.000000,2018-12-11 00:00:00,99301.000000,22638.480000,2018.000000,12.000000
std,2827.486899,NaN,32041.223413,625.302079,1.119373,3.499547

In [ ]:
# 5. Sauvegarde des donnees propres (super important pour Power BI et SQL)
df.to_csv("../data/cleaned_superstore.csv", index=False)